### ISSUE TITLE
Support single command with sub-commands

### ISSUE THREAD

**Issue by altendky** [Julian/venvs#29]
I would personally rather have `mkenv converge` than `convergeenvs` as a totally separate command.  I wouldn't see any need to eliminate `convergenvs` (or others), just add the subcommands.  Is this something you would be comfortable with?  No clue if/when I might make time to do this.  Presumably this would be after #15 and probably after #28 as well.

**Comment by Julian** [comment]
Hmmmmmm. Interesting.

So, maybe this is also related to #12 as well.

The "history" here is I wrote `mkenv` and friends first, and then `convergeenvs` came last, and then at the end I realized it was really the best idea, and have thought about removing everything else *but* it, but because it's missing features like #15, the rest have stuck around.

So, long story short, I'm open to this idea! And maybe even more so if there's a good name for this thing (that isn't taken on PyPI) that's a bit more focused...

**Comment by altendky** [comment]
`the-do-not-destroy-your-os-alternative-to-sudo-pip`?

**Comment by Julian** [comment]
Rolls off the tongue. I like it!

**Comment by Julian** [comment]
Closed in 75c42b458cc13829dc540059f4bb1dd9619c470f
