### ISSUE TITLE
Evade the virtualenv frankenstein py2+py3 issue

### ISSUE THREAD

**Issue by Julian** [Julian/venvs#5]
virtualenv is a wretched thing, and fork/noexecs, sometimes even across py2/py3 versions. This leads to broken things, so generally it's not safe to use `virtualenv -p somepython` -- each python should directly invoke `virtualenv.py`.

**Comment by altendky** [comment]
Is this still the case?  I guess you are referring to `thepython -m virtualenv` instead?  With 2/3 support and the ability to specify the Python version for each env (#15) it gets more complicated than just fixing #10.

So for #6 I was creating a zipapp.  Perhaps we should just do that for virtualenv and then we can use whatever Python the user wanted to run that single zipapp of virtualenv to create the env without any cross-Python funny business.  If zipapp's are satisfactorily 2/3 compatible...  I'll have to dig on that since my present understanding is to use pip to install into a directory that the zipapp gets created from.

**Comment by altendky** [comment]
Py2 doesn't have zipapp, but for this we don't really need whatever extra zipapp gets you it seems.  In #44 I just use a floating `pip install --target blah virtualenv` install with whatever Python is being used. 
 Just `sys.executable` for now but there will be more variety once I get to #15.  Doing this instead of a full zipapp avoids having to 'vendor' virtualenv in a zipapp and include it in distributions to be able to run in py2.

**Comment by Julian** [comment]
It's a bit easier to just use `thepython somevirtualenv.py` directly, rather than `-m`.

virtualenv.py itself is runnable as a single file across any python version.

**Comment by Julian** [comment]
(Either way though is fine, long as yeah it's not `-p` -- though, to put this in perspective, this specific issue can be super annoying if it crops up, but it's fairly rare that it does, say... I've seen it twice in my Python Career™)

**Comment by altendky** [comment]
Until #15...  hasn't this already been addressed by #43?  Additionally, #60 relates to keeping this ticket resolved when #15 gets implemented.

**Comment by Julian** [comment]
So neither #43 nor what I can tell #60 is trying to do solve this -- this ticket is that basically the only safe way to create virtualenvs is `targetpython virtualenv.py` -- `virtualenv.py -p targetpython` is essentially broken, because it forks/noexecs, so if the executable that virtualenv was installed to has imported some modules, those same modules will be in-memory when `targetpython` is switched to.

The most practical example of things that blow up when that happens is e.g. https://github.com/PythonCharmers/python-future/issues/148 which occurs because of the frankenstein set of modules that are first imported in the 2.7 host python and then stick around when the py3 version starts picking up where that left off.

Probably not being fully clear here but hopefully that issue gives you an idea of what this was trying to avoid.

**Comment by altendky** [comment]
I think they are all related.  But, after all this I noticed that you had recently implemented support for converging envs with python versions other than venvs itself is installed into and used `-p`.  So yes, Frankenstein came back to life.  #60 is a step in the the right direction.  It makes it so that virtualenv isn't required to be installed in the python used to run it, we always use the file installed into the venvs virtualenv.  Now that I see the change where you introduced `-p` I can expand #60 or do an additional PR to eliminate that recently introduced `-p` by using the target python rather than `sys.executable`.
